#!/usr/bin/env -S mise x lua@5.4 -- lua

local home = os.getenv("HOME") or ""
local config_dir = home .. "/.config/sketchybar"

package.path = config_dir .. "/?.lua;" .. config_dir .. "/?/init.lua;" .. package.path
package.cpath = package.cpath .. ";" .. home .. "/.local/share/sketchybar_lua/?.so"

Sbar = require("sketchybar")

Sbar.begin_config()
require("init")
Sbar.hotload(true)
Sbar.end_config()
Sbar.event_loop()
