#!/bin/bash

get_app_icon() {
  case "$1" in
    "Ableton Live" | "Live") echo ":ableton_live:" ;;
    "Activity Monitor") echo ":activity_monitor:" ;;
    "Acrobat Reader") echo ":adobe_acrobat_reader_dc:" ;;
    "Affinity Designer 2") echo ":affinity_designer:" ;;
    "Affinity Photo 2") echo ":affinity_photo:" ;;
    "Affinity Publisher 2") echo ":affinity_publisher:" ;;
    "Alacritty") echo ":alacritty:" ;;
    "Alfred") echo ":alfred:" ;;
    "Amazon Music") echo ":amazon_music:" ;;
    "Amazon Q") echo ":amazonq:" ;;
    "AnyDesk") echo ":anydesk:" ;;
    "AppCleaner") echo ":app_cleaner:" ;;
    "App Store") echo ":app_store:" ;;
    "Arc") echo ":arc:" ;;
    "Fusion" | "Fusion Service Utility") echo ":autodesk_fusion:" ;;
    "Bitwig Studio") echo ":bitwing_studio:" ;;
    "Blender") echo ":blender:" ;;
    "Books") echo ":books:" ;;
    "Brave Browser") echo ":brave_browser:" ;;
    "Calculator") echo ":calculator:" ;;
    "Calendar") echo ":calendar:" ;;
    "ChatGPT") echo ":chatgpt:" ;;
    "Google Chrome") echo ":chrome:" ;;
    "Claude") echo ":claude:" ;;
    "Clock") echo ":clock:" ;;
    "CotEditor") echo ":coteditor:" ;;
    "Cursor") echo ":cursor:" ;;
    "DataSpell") echo ":dataspell:" ;;
    "DEVONthink" | "DEVONthink 3") echo ":devonthink:" ;;
    "Discord") echo ":discord:" ;;
    "Docker Desktop") echo ":docker:" ;;
    "Drafts") echo ":drafts:" ;;
    "Easy CSV Editor") echo ":easy_csv_editor:" ;;
    "FaceTime") echo ":facetime:" ;;
    "Figma") echo ":figma:" ;;
    "Filen Drive") echo ":filen_drive:" ;;
    "Finder") echo ":finder_thick:" ;;
    "Firefox Developer Edition") echo ":firefox:" ;;
    "Font Book") echo ":font_book:" ;;
    "Ghostty") echo ":ghostty2:" ;;
    "GitHub Desktop") echo ":github_desktop:" ;;
    "Goodnotes") echo ":goodnotes:" ;;
    "Google Docs") echo ":google_docs:" ;;
    "Google Drive") echo ":google_drive:" ;;
    "Goggle Sheets") echo ":google_sheets:" ;;
    "Google Sheets") echo ":google_slides:" ;;
    "Hammerspoon") echo ":hammerspoon:" ;;
    "Hoppscotch") echo ":hoppscotch:" ;;
    "Inkscape") echo ":inkscape:" ;;
    "IntelliJ IDEA") echo ":intellij_idea:" ;;
    "iTerm2") echo ":iterm:" ;;
    "Karabiner-Elements") echo ":karabiner_elements:" ;;
    "Karabiner-EventViewer") echo ":karabiner_eventviewer:" ;;
    "Keynote") echo ":keynote:" ;;
    "KiCad") echo ":kicad:" ;;
    "Kindle") echo ":kindle:" ;;
    "kitty") echo ":kitty:" ;;
    "LaTeXiT") echo ":latexit:" ;;
    "LINE") echo ":line:" ;;
    "LTspice") echo ":ltspice:" ;;
    "Mail") echo ":mail:" ;;
    "Maps") echo ":maps:" ;;
    "Messages") echo ":messages:" ;;
    "Microsoft Excel") echo ":microsoft_excel:" ;;
    "Microsoft OneNote") echo ":microsoft_onenote:" ;;
    "Microsoft Outlook") echo ":microsoft_outlook:" ;;
    "Microsoft PowerPoint") echo ":microsoft_powerpoint:" ;;
    "Microsoft Remote Desktop") echo ":microsoft_remotedesktop:" ;;
    "Microsoft Teams classic") echo ":microsoft_teams:" ;;
    "Microsoft To Do") echo ":microsoft_todo:" ;;
    "Microsoft Word") echo ":microsoft_word:" ;;
    "Music") echo ":music:" ;;
    "Neovide" | "Neovim") echo ":neovide:" ;;
    "Notes") echo ":notes:" ;;
    "Notion") echo ":notion:" ;;
    "Notion Calendar") echo ":notion_calendar:" ;;
    "Numbers") echo ":numbers:" ;;
    "Obsidian") echo ":obsidian:" ;;
    "OneDrive") echo ":onedrive:" ;;
    "paw") echo ":paw:" ;;
    "Photos") echo ":photos:" ;;
    "Pixelmator" | "Pixelmator Pro") echo ":pixelmator:" ;;
    "Podcasts") echo ":podcasts:" ;;
    "Preview") echo ":preview_2:" ;;
    "PrusaSlicer") echo ":prusa_slicer:" ;;
    "PyCharm") echo ":pycharm:" ;;
    "pyhton") echo ":python:" ;;
    "python3.5" | "python3.6" | "python3.7" | "python3.8" | \
    "python3.9" | "python3.10" | "python3.11" | "python3.12" | "python3.13") echo ":python:" ;;
    "qBittorrent") echo ":qbittorrent:" ;;
    "QMK Toolbox") echo ":qmk:" ;;
    "REAPER") echo ":reaper:" ;;
    "Safari") echo ":safari:" ;;
    "Sequel Ace") echo ":sequel_ace:" ;;
    "Skim") echo ":skim:" ;;
    "Slack") echo ":slack:" ;;
    "Spark") echo ":spark:" ;;
    "Spotify") echo ":spotify:" ;;
    "Sublime Text") echo ":sublime_text:" ;;
    "System Settings") echo ":system_settings_simple_big:" ;;
    "Tailescale") echo ":tailscale:" ;;
    "TeamViewer") echo ":teamviewer:" ;;
    "Terminal") echo ":terminal:" ;;
    "TeXShop") echo ":texshop:" ;;
    "Things" | "Things 3") echo ":things:" ;;
    "TickTick") echo ":ticktick:" ;;
    "Todoist") echo ":todoist:" ;;
    "UpNote") echo ":upnote:" ;;
    "VESTA") echo ":vesta:" ;;
    "Vivaldi") echo ":vivaldi:" ;;
    "Code") echo ":vscode:" ;;
    "Warp") echo ":warp:" ;;
    "WezTerm") echo ":wezterm:" ;;
    "XQuartz") echo ":xquartz:" ;;
    "YouTube") echo ":youtube:" ;;
    "YouTube Music") echo ":youtube_music:" ;;
    "Zed") echo ":zed:" ;;
    "Zen Browser") echo ":zen_browser:" ;;
    "zoom" | "zoom.us") echo ":zoom:" ;;
    *) echo ":default:" ;;  # fallback
  esac
}
