#!/usr/bin/env -S mise x lua@5.4 -- lua

local home = os.getenv("HOME") or ""
local config_dir = home .. "/.config/sketchybar"

local media_daemon = config_dir .. "/helpers/media_daemon.sh"
os.execute("pkill -f " .. string.format("%q", media_daemon) .. " >/dev/null 2>&1")
os.execute(string.format("%q", media_daemon) .. " >/dev/null 2>&1 &")

package.path = config_dir .. "/?.lua;" .. config_dir .. "/?/init.lua;" .. package.path
package.cpath = package.cpath .. ";" .. home .. "/.local/share/sketchybar_lua/?.so"

Sbar = require("sketchybar")

Sbar.begin_config()
require("init")
Sbar.hotload(true)
Sbar.end_config()
Sbar.event_loop()
