#!/usr/bin/env bash

# Shared spacing/update constants
INNER_PADDING=4
OUTER_PADDING=8
EAGER_FREQUENCY=1
LAZY_FREQUENCY=300

# Bar/default geometry
BAR_HEIGHT=44
BAR_MARGIN=0
BAR_Y_OFFSET=0
BAR_CORNER_RADIUS=0
BAR_BORDER_WIDTH=0
BAR_BLUR_RADIUS=0
BAR_PADDING_LEFT=4
BAR_PADDING_RIGHT=4
BAR_COLOR_ALPHA=20
BAR_BORDER_ALPHA=80

DEFAULT_BG_HEIGHT=36
DEFAULT_BG_Y_OFFSET=0
DEFAULT_BG_PADDING_LEFT=2
DEFAULT_BG_PADDING_RIGHT=2
DEFAULT_BG_CORNER_RADIUS=4
DEFAULT_BG_BORDER_WIDTH=0
DEFAULT_BG_ALPHA=80

# Shared typography
FONT="Hack Nerd Font:BOLD:15.0"
PILL_ICON_SIZE=18
PILL_LABEL_SIZE=16

# Shared surfaces/colors (expects colors.sh already sourced)
PILL_LABEL_COLOR="$TEXT_LIGHTEST"
PILL_BG_COLOR="$(set_alpha "$BACKGROUND_DARKEST" 82)"
PILL_BORDER_COLOR="$(set_alpha "$CYAN" 35)"

# Shared geometry
PILL_CORNER_RADIUS=4
PILL_BORDER_WIDTH=1
PILL_Y_OFFSET=0

# Dynamic label constraints
FRONT_APP_WIDTH=320
FRONT_APP_MAX_CHARS=24

# Monitor density profiles
apply_density_profile() {
  local profile="${1:-comfortable}"

  case "$profile" in
    compact)
      BAR_HEIGHT=34
      DEFAULT_BG_HEIGHT=27
      FONT="Hack Nerd Font:BOLD:13.0"
      PILL_ICON_SIZE=15
      PILL_LABEL_SIZE=13
      INNER_PADDING=3
      OUTER_PADDING=6
      FRONT_APP_WIDTH=220
      FRONT_APP_MAX_CHARS=16
      ;;
    comfortable|*)
      BAR_HEIGHT=44
      DEFAULT_BG_HEIGHT=36
      FONT="Hack Nerd Font:BOLD:15.0"
      PILL_ICON_SIZE=18
      PILL_LABEL_SIZE=16
      INNER_PADDING=4
      OUTER_PADDING=8
      FRONT_APP_WIDTH=320
      FRONT_APP_MAX_CHARS=24
      ;;
  esac
}
